Return an error when the promises are rejected (fixes #16)
brave/https-everywhere-builder pull request #17
Opened 2019-05-22 20:47 UTC by fmarier

This is to ensure that our failed Jenkins jobs are actually flagged as failed.

2019-05-23 21:21 UTC, fmarier commented
The Travis CI build error is not due to this PR: https://github.com/brave/devops/issues/1057

2019-05-24 22:13 UTC, bsclifton requested changes
got some errors running the steps that are supposed to run via CI 😄 

Can you fix the lint errors (ex: test with `npm run lint`)

Besides that, there's also an npm audit fix we can run... I'll do a commit updating that 😄

2019-05-24 22:22 UTC, fmarier commented
Lint clean and rebased on top of the latest master.

2019-05-24 22:25 UTC, bsclifton approved these changes
Changes look great! 😄👍 Verified both checks pass manually (since travis is having a problem with node at the moment)

2019-05-24 22:26 UTC, merged